-function(){"use strict";var e;var k=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},l=function(a){if(k(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&k(a))return a;return null};var m=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var p=function(a){setTimeout(a,0)};var q=function(a,b,c){var d;c?(d=document.createEvent("CustomEvent"),d.initCustomEvent(a,!0,!0,c)):(d=document.createEvent("Event"),d.initEvent(a,!0,!0));b.dispatchEvent(d);return d},r=function(a){p(function(){q("allframesviewed",a,void 0)})},u=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var v=["-ms-","-moz-","-webkit-",""];var w=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},x=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(w(m(a[c])))}return b},y=function(a,b,c){q(b,a,{id:c||a.currentIndex})},z=function(a,b){return(a%b+b)%b};var A=function(){};goog.inherits(A,HTMLElement);e=A.prototype;
e.createdCallback=function(){this.o=!1;this.f=null;this.a=0;this.F=1;this.b=-1;this.D=0;this.c=[];var a=document.createElement("gwd-gesture");a.className="gesture";this.m=a;this.C=this.L.bind(this);this.B=this.M.bind(this);this.A=this.K.bind(this);this.l=q.bind(null,"firstinteraction",this);this.w=this.J.bind(this);this.j=[];this.v=0;this.g=-1;this.h=null;this.u=this.hasAttribute("images");this.i=null;Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.G.bind(this)});Object.defineProperty(this,
"frameSnapInterval",{enumerable:!0,get:this.I.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.H.bind(this)})};e.attachedCallback=function(){var a=this.m;a.addEventListener("trackstart",this.C,!1);a.addEventListener("track",this.B,!1);a.addEventListener("tap",this.A,!1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=l(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
e.detachedCallback=function(){var a=this.m;a.removeEventListener("trackstart",this.C,!1);a.removeEventListener("track",this.B,!1);a.removeEventListener("tap",this.A,!1);-1!=this.g&&(B(this,this.g),C(this))};e.goToFrame=function(a,b,c){C(this);if(0<a&&a<=this.a){var d=z(a-1,this.a);b=b||"slide";c||(c=this.b,c=d>c==this.a/2>Math.abs(d-c)?"forwards":"backwards");y(this,"frameactivated",a);this.s(this.b,d,b,c,300)}};
e.rotateOnce=function(a,b){C(this);var c=a&&b&&"string"==typeof a&&"number"==typeof b,d=(c?a:b)||"forwards",g=(c?b:a)||300*this.a;if(1<this.a){var f=this.b,h=z(this.b+("left"==d||"backwards"==d?-1:1),this.a);p(function(){this.s(h,f,"slide",d,g/this.a,!0)}.bind(this))}};e.gwdIsLoaded=function(){return this.o};
e.gwdLoad=function(){if(!this.o&&!this.f){var a;if(this.u)a=x(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var g=a[c];g.nodeType==Node.ELEMENT_NODE&&b.push(g)}a=b}this.c=a;D(this)}};
var D=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.f&&a.f.removeEventListener("pageload",a.w,!1);for(var b=a.c,c=document.createElement("div","gwd-page"),d,g=0;g<b.length;++g){for(var f=d=b[g],h=void 0,n=void 0,t=0;t<v.length;++t)h=v[t]+"user-select",n="none",f.style.setProperty(h,n);d.classList.add("frame");c.appendChild(d)}u(c,c.gwdLoad.bind(c));a.f=c;c.addEventListener("pageload",a.w,!1);a.appendChild(c);a.appendChild(a.m)};e=A.prototype;
e.J=function(a){if(this.f===a.target){a=this.c;for(var b=this.clientWidth,c=this.clientHeight,d,g=b/c,f,h,n=0;n<a.length;++n)d=a[n],"img"==d.tagName.toLowerCase()&&(f=d.offsetWidth/d.offsetHeight,g>f?(h=c*f,f=c):(h=b,f=b/f),d.style.width=h+"px",d.style.height=f+"px");this.o=!0;this.removeChild(this.f);this.a=this.c.length;this.j=[];this.v=this.a;B(this,0);this.f=null;q("imagesloaded",this);q("allframesloaded",this);this.hasAttribute("autoplay")&&setTimeout(this.rotateOnce.bind(this),0);q("ready",
this)}};e.attributeChangedCallback=function(a){"images"==a&&(C(this),this.u=!0,this.a=0,this.b=-1,this.c=x(this.getAttribute(a)),D(this))};e.L=function(){C(this);this.a&&(this.D=this.b)};e.M=function(a){this.a&&(this.l&&(this.l(),this.l=null),a=z(this.D+Math.round(a.dx/50),this.a),this.b!=a&&this.c[a]&&(y(this,"frameactivated",a+1),B(this,a)))};e.K=function(){this.a&&y(this,"frametap")};
var B=function(a,b){if(a.b!=b&&a.c[b]){a.b=b;var c=a.i;a.i=a.c[b];a.appendChild(a.i);c&&a.removeChild(c);y(a,"frameshown");a.j[b]||(a.j[b]=!0,--a.v||r(a))}};A.prototype.s=function(a,b,c,d,g,f){"none"==c&&(a=b);B(this,a);f&&y(this,"frameactivated",a+1);a!=b?(this.g=b,a=z(a+("left"==d||"backwards"==d?-1:1),this.a),this.h=setTimeout(this.s.bind(this,a,b,c,d,g,f),g)):(this.h=null,this.g=-1)};var C=function(a){-1!=a.g&&(clearTimeout(a.h),a.h=null,a.g=-1,y(a,"frameactivated",a.b))};e=A.prototype;
e.G=function(){return this.a?this.b+1:void 0};e.getFrame=function(a){return this.c[a-1]};e.goForwards=function(){this.goToFrame(this.b+2,"none")};e.goBackwards=function(){this.goToFrame(this.b,"none")};e.I=function(){return this.F};e.H=function(){return this.a};document.registerElement("gwd-360gallery",{prototype:A.prototype});}()
