(function(){'use strict';var e;var l=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},m=function(a){if(l(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&l(a))return a;return null};var n=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var p=function(a,b,c){if(c){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);b.dispatchEvent(d);return d},q=function(a){setTimeout(function(){p("allframesviewed",a,void 0)},0)},r=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var t=["-ms-","-moz-","-webkit-",""];var u=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},v=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(u(n(a[c])))}return b},w=function(a,b,c){p(b,a,{id:c||a.currentIndex})},x=function(a,b){return(a%b+b)%b},y=function(a,b,c){return x(a+("left"==b||"backwards"==b?-1:1),c)};var z=function(){};goog.inherits(z,HTMLElement);e=z.prototype;
e.createdCallback=function(){this.s=!1;this.g=null;this.a=0;this.G=1;this.b=-1;this.v=0;this.c=[];var a=document.createElement("gwd-gesture");a.className="gesture";this.o=a;this.F=this.M.bind(this);this.D=this.N.bind(this);this.C=this.L.bind(this);this.m=p.bind(null,"firstinteraction",this);this.B=this.K.bind(this);this.l=[];this.A=0;this.f=-1;this.i=null;this.w=this.hasAttribute("images");this.h=this.hasAttribute("wrap");this.j=null;Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.H.bind(this)});
Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.J.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.I.bind(this)})};e.attachedCallback=function(){var a=this.o;a.addEventListener("trackstart",this.F,!1);a.addEventListener("track",this.D,!1);a.addEventListener("tap",this.C,!1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=m(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
e.detachedCallback=function(){var a=this.o;a.removeEventListener("trackstart",this.F,!1);a.removeEventListener("track",this.D,!1);a.removeEventListener("tap",this.C,!1);-1!=this.f&&(A(this,this.f),B(this))};e.goToFrame=function(a,b,c){var d=a-1;B(this);if(0<=d&&d<this.a&&d!=(-1!=this.f?this.f:this.b)){b=b||"slide";if(!c){c=this.b;var f=Math.abs(d-c);c=d>c==(!this.h||this.a/2>f)?"forwards":"backwards"}w(this,"frameactivated",a);this.u(y(this.b,c,this.a),d,b,c,300)}};
e.rotateOnce=function(a,b){B(this);var c=a&&b&&"string"==typeof a&&"number"==typeof b,d=(c?a:b)||"forwards",f=(c?b:a)||300*this.a;if(1<this.a){var g=this.b,h=y(this.b,d,this.a);setTimeout(function(){this.u(h,g,"slide",d,f/this.a,!0)}.bind(this),0)}};e.stopRotation=function(){B(this)};e.gwdIsLoaded=function(){return this.s};
e.gwdLoad=function(){if(!this.s&&!this.g){if(this.w)var a=v(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var f=a[c];f.nodeType==Node.ELEMENT_NODE&&b.push(f)}a=b}this.c=a;C(this)}};
var C=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.g&&a.g.removeEventListener("pageload",a.B,!1);for(var b=a.c,c=document.createElement("div","gwd-page"),d,f=0;f<b.length;++f){d=b[f];for(var g,h=d,k=0;k<t.length;++k)g=t[k]+"user-select",h.style.setProperty(g,"none");d.classList.add("frame");c.appendChild(d)}r(c,c.gwdLoad.bind(c));a.g=c;c.addEventListener("pageload",a.B,!1);a.appendChild(c);a.appendChild(a.o)};e=z.prototype;
e.K=function(a){if(this.g===a.target){a=this.c;for(var b=this.clientWidth,c=this.clientHeight,d,f=b/c,g,h,k=0;k<a.length;++k)d=a[k],"img"==d.tagName.toLowerCase()&&(g=d.offsetWidth/d.offsetHeight,f>g?(h=c*g,g=c):(h=b,g=b/g),d.style.width=h+"px",d.style.height=g+"px");this.s=!0;this.removeChild(this.g);this.a=this.c.length;this.l=[];this.A=this.a;A(this,0);this.g=null;p("imagesloaded",this);p("allframesloaded",this);this.hasAttribute("autoplay")&&setTimeout(this.rotateOnce.bind(this),0);p("ready",
this)}};e.attributeChangedCallback=function(a){"images"==a&&(B(this),this.w=!0,this.a=0,this.b=-1,this.c=v(this.getAttribute(a)),C(this));this.h=this.hasAttribute("wrap")};e.M=function(){B(this);this.a&&(this.v=this.b)};e.N=function(a){this.a&&(this.m&&(this.m(),this.m=null),a=Math.round(a.dx/50),a=this.h?x(this.v+a,this.a):Math.max(0,Math.min(this.a-1,this.v+a)),this.b!=a&&this.c[a]&&(w(this,"frameactivated",a+1),A(this,a)))};e.L=function(){this.a&&w(this,"frametap")};
var A=function(a,b){if(a.b!=b&&a.c[b]){a.b=b;var c=a.j;a.j=a.c[b];a.appendChild(a.j);c&&a.removeChild(c);w(a,"frameshown");a.l[b]||(a.l[b]=!0,--a.A||q(a))}};z.prototype.u=function(a,b,c,d,f,g){"none"==c&&(a=b);A(this,a);g&&w(this,"frameactivated",a+1);a!=b?(this.f=b,a=y(a,d,this.a),this.i=setTimeout(this.u.bind(this,a,b,c,d,f,g),f)):(this.i=null,this.f=-1)};var B=function(a){-1!=a.f&&(clearTimeout(a.i),a.i=null,a.f=-1,w(a,"frameactivated",a.b))};e=z.prototype;
e.H=function(){return this.a?this.b+1:void 0};e.getFrame=function(a){return this.c[a-1]};e.goForwards=function(){var a=x(this.b+1,this.a);!this.h&&a<this.b||this.goToFrame(a+1)};e.goBackwards=function(){var a=x(this.b-1,this.a);!this.h&&a>this.b||this.goToFrame(a+1)};e.J=function(){return this.G};e.I=function(){return this.a};document.registerElement("gwd-360gallery",{prototype:z.prototype});}).call(this);
