-function(){"use strict";var g=function(a,b,d){return a.hasAttribute(b)?a.getAttribute(b):d};var h=["-ms-","-moz-","-webkit-",""],k=function(a,b,d){for(var c,e,f=0;f<h.length;++f)c=h[f]+b,e=""+d,a.style.setProperty(c,e)};var l=function(){return"ontouchstart"in window||0<window.navigator.MaxTouchPoints||0<window.navigator.msMaxTouchPoints};var m=["ICALENDAR","GOOGLE","WINDOWS_LIVE","YAHOO"],n={I:"description",J:"end-date",K:"end-time",L:"event-title",LOCATION:"location",N:"start-date",O:"start-time",P:"timezone",ICALENDAR:"icalendar",GOOGLE:"google",WINDOWS_LIVE:"windows-live",YAHOO:"yahoo",BG_COLOR:"bg-color",FONT_COLOR:"font-color",F:"font-family",G:"font-size",H:"font-weight",M:"highlight-color"},p={ICALENDAR:"gwd-icalendar-",GOOGLE:"gwd-google-calendar-",WINDOWS_LIVE:"gwd-windows-live-calendar-",YAHOO:"gwd-yahoo-calendar-"},q={ICALENDAR:"iCalendar",
GOOGLE:"Google",WINDOWS_LIVE:"Windows Live",YAHOO:"Yahoo"},r={BG_COLOR:"#fff",FONT_COLOR:"#000",X:"0px 5px 10px rgba(0, 0, 0, 0.292969)",Y:"0px -5px 10px rgba(0, 0, 0, 0.292969)",F:"arial, helvetica, sans-serif",G:"12pt",H:"normal",HIDDEN:"hidden",M:"#e0e0e0",VISIBLE:"visible"},u={I:"description",J:"endDate",K:"endTime",L:"eventTitle",LOCATION:"location",N:"startDate",O:"startTime",P:"timezone"},v={U:"background-color",V:"border-color",W:"box-shadow",Z:"color",$:"display",F:"font-family",G:"font-size",
H:"font-weight",aa:"top",ba:"visibility"};var w=function(a,b,d){var c;d?(c=document.createEvent("CustomEvent"),c.initCustomEvent(a,!0,!0,d)):(c=document.createEvent("Event"),c.initEvent(a,!0,!0));b.dispatchEvent(c);return c};var x=/-|:|\..*\d/g,y=/^\D|^$/,z=/\d(?=pt|px|em|%)/i,A=/8_1_3|8_2/,C=function(a,b,d,c,e){var f=B(new Date);return"BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Add To Calendar//\nBEGIN:VEVENT\nUID:"+f+"@*.2mdn.net\nDTSTAMP:"+f+"\nDTSTART:"+b+"\nDTEND:"+d+"\nSUMMARY:"+a+"\nDESCRIPTION:"+c+"\nLOCATION:"+e+"\nEND:VEVENT\nEND:VCALENDAR"},D=function(){return window.navigator.userAgent||""},E=function(a,b,d){w(b,d,{url:a}).detail.handled||window.open(a)},F=function(){var a=!l()&&-1==D().indexOf("Chrome")&&-1!=
(window.navigator.userAgent||"").indexOf("WebKit"),b=-1!=D().indexOf("iPad")&&A.test(D());return!!window.navigator.msSaveBlob||!a&&!b&&-1==D().indexOf("CriOS")},G=function(a,b){if(F()){var d=a.eventTitle,c=C(d,a.startDate,a.endDate,a.description,a.location),e="text/calendar;charset="+document.characterSet,c=new Blob([c],{type:e}),f=d+".ics";if(window.navigator.msSaveBlob)window.navigator.msSaveBlob(c,f);else{var t=new FileReader;t.onload=function(){var a=t.result,b=document.createElement("a");if("download"in
b){var c=new MouseEvent("click");b.href=a;b.download=f;b.type=e;b.dispatchEvent(c)}else window.location.href=a};t.readAsDataURL(c)}w("icalendar",b)}},H=function(a,b){var d="&text="+a.eventTitle+"&dates="+a.startDate+"/"+a.endDate+"&details="+a.description+"&location="+a.location;E(-1==(window.navigator.userAgent||"").indexOf("WebKit")&&-1==(window.navigator.userAgent||"").indexOf("Android")||-1==D().indexOf("Mobile")||-1!=D().indexOf("iPad")?"https://www.google.com/calendar/render?action=TEMPLATE"+
d:"https://www.google.com/calendar/gpcal?#~calendar:view=e"+d,"google",b)},I=function(a,b){E("https://calendar.live.com/calendar/calendar.aspx?rru=addevent&summary="+a.eventTitle+"&dtstart="+a.startDate+"&dtend="+a.endDate+"&description="+a.description+"&location="+a.location,"windowslive",b)},J=function(a,b,d){a="https://calendar.yahoo.com/?v=60&title="+a.eventTitle+"&st="+a.startDate+"&dur="+b+"&desc="+a.description+"&in_loc="+a.location;E(b?a:"https://calendar.yahoo.com/","yahoo",d)},B=function(a){return a.toISOString().replace(x,
"")};function K(a,b,d,c){this.a=a;this.g=b;this.i=d;this.f=c;this.v=this.w=this.A=this.h=this.b=null;this.s=["click","touchend"];this.u=Math.random().toString(36).substring(2,6);this.b=document.createElement("div");this.h=this.C.bind(this);this.A=this.T.bind(this);this.w=this.S.bind(this);for(a=0;a<this.i.length;a++)b=this.i[a].className,F()||"gwd-icalendar-"!=b||(this.i.splice(a,1),b=this.i[a].className),d=document.createTextNode(this.i[a].text),c=document.createElement("gwd-taparea"),c.setAttribute("class",
b+this.u),c.appendChild(d),c.addEventListener("action",this.h),l()||c.addEventListener("mouseover",this.A),c.addEventListener("mouseout",this.w),this.b.appendChild(c);L(this);this.f.appendChild(this.b);this.v=this.R.bind(this);for(a=0;a<this.s.length;a++)document.body.addEventListener(this.s[a],this.v,!0)}
var M=function(a){for(var b=0;b<a.s.length;b++)document.body.removeEventListener(a.s[b],a.v,!0);for(b=a.b.firstChild;b;b=b.nextSibling)b.removeEventListener("action",a.h),b.removeEventListener("mouseover",a.A),b.removeEventListener("mouseout",a.w);a.s.length=0;a.v=null;a.h=null;a.A=null;a.w=null;a.f.removeChild(a.b);a.b=null;a.g=null;a.i=null;a.a=null},L=function(a){for(var b in v){var d=v[b];if("visibility"!=d){"background-color"==d||"border-color"==d?b="BG_COLOR":"color"==d&&(b="FONT_COLOR");var c=
g(a.f,n[b],r[b]);"font-size"==d&&(c=y.test(c)||z.test(c)?c:c+"pt");k(a.b,d,c)}}},N=function(a,b){var d=a.f.offsetHeight+a.b.offsetHeight+3;d+a.f.offsetTop>a.f.parentNode.clientHeight?(k(a.b,"top","-"+d+"px"),k(a.b,"box-shadow","0px -5px 10px rgba(0, 0, 0, 0.292969)")):(k(a.b,"box-shadow","0px 5px 10px rgba(0, 0, 0, 0.292969)"),a.b.style.removeProperty("top"));k(a.b,"visibility",b?"visible":"hidden")};K.prototype.R=function(a){"visible"==this.b.style.visibility&&(a.preventDefault(),N(this,!1))};
K.prototype.C=function(a){switch(a.target.className){case "gwd-icalendar-"+this.u:G(this.a,this.f);break;case "gwd-google-calendar-"+this.u:H(this.a,this.f);break;case "gwd-windows-live-calendar-"+this.u:I(this.a,this.f);break;case "gwd-yahoo-calendar-"+this.u:J(this.a,this.g,this.f)}};K.prototype.T=function(a){var b=g(this.f,"highlight-color","#e0e0e0");k(a.target,"background-color",b)};K.prototype.S=function(a){a.target.style.removeProperty("background-color")};var O=function(){};goog.inherits(O,HTMLElement);O.prototype.createdCallback=function(){this.c=this.g=this.B=this.a=null;this.o=this.m=this.j=this.l=!1;this.h=this.C.bind(this);this.D=document.createElement("gwd-taparea");if(0<this.childNodes.length)for(this.B=this.innerHTML;this.firstChild;)this.removeChild(this.firstChild);this.appendChild(this.D)};O.prototype.attachedCallback=function(){P(this);Q(this);this.D.addEventListener("action",this.h)};
O.prototype.attributeChangedCallback=function(a){switch(a){case "description":case "event-title":case "end-date":case "end-time":case "location":case "start-date":case "start-time":case "timezone":P(this);break;case "icalendar":case "google":case "windows-live":case "yahoo":Q(this);break;case "bg-color":case "font-color":case "font-family":case "font-size":case "font-weight":this.c&&L(this.c)}};
O.prototype.detachedCallback=function(){this.D.removeEventListener("action",this.h);this.c&&(M(this.c),this.c=null);R(this)};O.prototype.C=function(){if(this.a){var a=this.j&&!this.l&&!this.m&&!this.o,b=this.m&&!this.l&&!this.j&&!this.o,d=this.o&&!this.l&&!this.j&&!this.m;!this.l||this.j||this.m||this.o?a?H(this.a,this):b?I(this.a,this):d?J(this.a,this.g,this):this.c&&N(this.c,!0):G(this.a,this)}};
var R=function(a){a.g=null;a.a=null},P=function(a){a.a={};for(var b in u){var d=g(a,n[b],"");a.a[u[b]]=d}if(""==a.a.eventTitle)R(a);else if(""==a.a.endDate&&(a.a.endDate=a.a.startDate),""==a.a.endTime&&(a.a.endTime=a.a.startTime),b=new Date(a.a.startDate+" "+a.a.startTime+" "+a.a.timezone),d=new Date(a.a.endDate+" "+a.a.endTime+" "+a.a.timezone),isNaN(b)||isNaN(d))R(a);else if(b.getTime()>d.getTime())R(a);else{var c;var e=d.getTime()-b.getTime();c=Math.floor(e/36E5);e=(Math.floor(e/6E4)-60*c).toString();
c=c.toString();2<c.length?c=null:(2>c.length&&(c="0"+c),2>e.length&&(e="0"+e),c+=e);a.g=c;a.B&&(a.a.description=a.B);a.a.startDate=B(b);a.a.endDate=B(d);a.c&&(b=a.c,d=a.g,b.a=a.a,b.g=d)}},Q=function(a){var b=0;a.l=a.hasAttribute("icalendar");a.l&&b++;a.j=a.hasAttribute("google");a.j&&b++;a.m=a.hasAttribute("windows-live");a.m&&b++;a.o=a.hasAttribute("yahoo");a.o&&b++;a.c&&(M(a.c),a.c=null);if(1<b){for(var b=[],d=0;d<m.length;d++){var c=m[d];if(a.hasAttribute(n[c])){var e={};e.className=p[c];e.text=
q[c];b.push(e)}}0!=b.length&&(a.c=new K(a.a,a.g,b,a))}};document.registerElement("gwd-addtocalendar",{prototype:O.prototype});}()
