(function(){var f;var l=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},m=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},p=function(a){if(m(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&m(a))return a;return null},u=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},v=function(a,
b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var w=["-ms-","-moz-","-webkit-",""],x=function(a,b,c,d){for(var e,h,g=0;g<w.length;++g)e=w[g]+b,h=(d?w[g]:"")+c,a.style.setProperty(e,h)};var y=function(a,b,c){if(c){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);b.dispatchEvent(d);return d},z=function(a,b){setTimeout(function(){y("autoplayended",a,b)},0)},A=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var B=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var C=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},D=function(a,b){this.h=a;this.j=null;this.ga=b;this.B=!1};
D.prototype.play=function(a,b,c){if(this.h.frameCount&&null==this.j){b=b||"forwards";if(c){var d=Math.floor(a/c);a=c}else d=this.h.frameCount,a/=d;var e=[],h=C(this.h);c=h;for(var g=0;g<d;g++){if(0<g||!this.ga)c=E(c+F(b,1),this.h.frameCount);e.push(c)}b=function(){if(e.length){var a=e.shift();this.B=!0;this.h.goToFrame(a+1);this.B=!1;G(this.h,"frameautoplayed",a+1)}else this.stop(!0),this.h.goToFrame(h+1)}.bind(this);this.j=setInterval(b,a);setTimeout(b)}};
D.prototype.stop=function(a){!this.B&&this.j&&(clearInterval(this.j),z(this.h,{completed:!!a}),this.j=null)};
var H=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},I=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(H(B(a[c])))}return b},J=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];"img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")&&(null!=b?e.setAttribute("scaling",b):e.removeAttribute("scaling"))}},G=function(a,b,c){y(b,a,{id:c||a.currentIndex})},K=function(a,b){var c=b.length;b=b.splice(0,
c);for(var d,e=0;e<c;e++)d=b[e],"frameshown"==d?G(a,d):y(d,a)},F=function(a,b){return"left"==a||"backwards"==a?-b:b},E=function(a,b){return(a%b+b)%b},L=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.pause()})},aa=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.play()})};var M=function(a){var b=u(a,"frame-width",-1);-1==b&&(b=parseInt(.8*a.clientWidth,10));var c=a.hasAttribute("show-reflection"),d=u(a,"frame-height",-1);-1==d&&(d=c?parseInt(4*a.clientHeight/7,10):parseInt(6*a.clientHeight/7,10));var e=u(a,"neighbor-translation-x",-1);-1==e&&(e=parseInt(b/8,10));if(a.hasAttribute("neighbor-translation-x"))a:{var h=d;b:switch(a.getAttribute("clamp-frame-size-to-image")){case "true":var g=!0;break b;case "false":g=!1;break b;default:g=!0}if(g){var k=a.hasAttribute("scaling")?
a.getAttribute("scaling"):"contain";if((g="contain"==k)||"none"==k){k=-1;for(var n=a.frameCount,q=0;q<n;q++){var r=a.getFrame(q+1);if("img"!=r.tagName.toLowerCase()||"gwd-image"!=r.getAttribute("is"))break a;var t=r;r=t.assetWidth;t=t.assetHeight;0<r&&0<t&&(k=Math.max(k,g?r/t<b/h?r/t*h:b:r))}b=-1!=k?Math.min(b,k):b}}}h=u(a,"neighbor-translation-y",-1);-1==h&&(h=parseInt(d/-10,10));g=u(a,"neighbor-translation-z",-1);-1==g&&(g=-d);a.f&&(d-=36);k=[];if(n=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):
"")for(n=n.split(","),q=0;q<n.length;q++)k[q]=n[q].trim();return{autoplay:a.hasAttribute("autoplay"),H:k,s:b,V:d,Z:u(a,"neighbor-rotation-y",38),$:e,L:h,aa:g,transitionDuration:u(a,"transition-duration",600),ja:c,ha:u(a,"start-frame",2)}},N=function(a,b,c,d,e){b="translate3d("+b+"px, "+c+"px, "+d+"px)";e&&(b="rotate3d(0, 1, 0, "+e+"deg) "+b);x(a,"transform",b)},O=function(a,b){x(a,"transition","transform "+b+"ms",!0)};var P=function(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ia=function(a,c,h){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var Q=function(){};P(Q,HTMLElement);f=Q.prototype;f.createdCallback=function(){this.frames=[];this.b=null;this.a=0;this.o=1;this.m=new D(this,!0);Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.W.bind(this)});Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.Y.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.X.bind(this)});this.N=this.hasAttribute("pause-front-media");this.O=this.hasAttribute("resume-next-media")};
f.attributeChangedCallback=function(a){switch(a){case "pause-front-media":this.N=this.hasAttribute("pause-front-media");break;case "resume-next-media":this.O=this.hasAttribute("resume-next-media")}};f.getFrame=function(a){if(0!=this.a)return this.frames[a-1]};f.gwdLoad=function(){};f.gwdIsLoaded=function(){return!0};f.goToFrame=function(a,b){this.stopRotation();0!=this.a&&(a>this.a?a=this.a:1>a&&(a=1),this.J(a,b))};f.J=function(a){this.b=a-1};
var R=function(a,b,c,d){if(null!=a.b){var e=E(a.b+F(b,a.o||1),a.o*Math.ceil(a.a/a.o));null!=d&&!d&&("forwards"==b&&e<a.b||"backwards"==b&&e>a.b)||a.goToFrame(e+1,c||"slide")}};f=Q.prototype;f.goBackwards=function(a,b){return R(this,"backwards",a,b)};f.goForwards=function(a,b){return R(this,"forwards",a,b)};f.rotateOnce=function(a,b){this.m.play(a||0,b)};f.stopRotation=function(){this.m.stop()};f.W=function(){return 0<this.a?this.b+1:void 0};f.Y=function(){return this.o};f.X=function(){return this.a};
var S=function(a,b){null!=a.b&&a.b!=b&&(a.N&&L(a.frames[a.b]),a.O&&aa(a.frames[b]))};var T=function(){};P(T,Q);f=T.prototype;
f.createdCallback=function(){T.P.createdCallback.call(this);this.C=!1;this.g=null;this.K=-1;this.F=0;var a=document.createElement("gwd-gesture");a.className="gesture";this.i=a;this.U=this.ea.bind(this);this.T=this.fa.bind(this);this.S=this.da.bind(this);this.R=this.ca.bind(this);this.w=y.bind(null,"firstinteraction",this);this.M=this.ba.bind(this);this.G=!1;this.D=[];this.l=K.bind(null,this,this.D);this.v=[];this.I=0;if(this.A=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.c=
null;this.u=0;this.m=new D(this,!1);this.f=null};
f.attachedCallback=function(){var a=this.i;this.u=this.u||this.clientWidth/2;a.addEventListener("trackstart",this.U,!1);a.addEventListener("track",this.T,!1);a.addEventListener("trackend",this.S,!1);a.addEventListener("tap",this.R,!1);this.addEventListener("transitionend",this.l,!1);this.addEventListener("webkitTransitionEnd",this.l,!1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=p(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&
this.gwdLoad()}};f.detachedCallback=function(){var a=this.i;a.removeEventListener("trackstart",this.U,!1);a.removeEventListener("track",this.T,!1);a.removeEventListener("trackend",this.S,!1);a.removeEventListener("tap",this.R,!1);this.removeEventListener("transitionend",this.l);this.removeEventListener("webkitTransitionEnd",this.l)};f.J=function(a,b){b="none"!=b;var c=this.c.transitionDuration;S(this,a-1);U(this,b?c:0);V(this,a-1)};
f.rotateOnce=function(a,b){this.m.play(a||this.c.transitionDuration*this.a,b)};f.gwdIsLoaded=function(){return this.C};f.gwdLoad=function(){if(!this.C&&!this.g){if(this.A)var a=I(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;W(this)}};
var W=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.f=null;a.g&&a.g.removeEventListener("pageload",a.M,!1);for(var b=a.frames,c=document.createElement("div","gwd-page"),d,e=0;e<b.length;++e)d=b[e],x(d,"user-select","none"),d.classList.add("frame"),c.appendChild(d);A(c,c.gwdLoad.bind(c));a.g=c;c.className=a.hasAttribute("show-reflection")?"container reflection":"container";c.addEventListener("pageload",a.M,!1);J(a.frames,a.getAttribute("scaling"));a.appendChild(c);a.appendChild(a.i)};
T.prototype.ba=function(a){if(this.g===a.target){this.C=!0;this.a=this.frames.length;this.v=[];this.I=this.a;X(this);if(this.a){a=this.c.ha-1;if(0>a||a>=this.a)a=0;U(this,0);V(this,a);this.c.autoplay&&setTimeout(this.rotateOnce.bind(this),0)}Y(this);y("allframesloaded",this);y("ready",this)}};
T.prototype.attributeChangedCallback=function(a){T.P.attributeChangedCallback.call(this,a);switch(a){case "images":this.A=!0;this.a=0;this.b=null;this.frames=I(this.getAttribute(a));W(this);break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":Y(this);break;case "scaling":J(this.frames,this.getAttribute("scaling"));break;case "style":case "class":break;default:this.c=M(this)}};
var X=function(a){a.c=M(a);for(var b=0,c,d=0;d<a.frames.length;d++)c=a.frames[d],c.style.left=b+"px",c.style.width=a.c.s+"px",c.style.height=a.c.V+"px",b+=a.c.s};T.prototype.ea=function(){null!=this.b&&(this.stopRotation(),this.F=this.b,U(this,0))};T.prototype.fa=function(a){if(this.a){this.w&&(this.w(),this.w=null);a=-a.dx/this.c.s;var b=Math.round(a);Z(this,this.F+b,a-b)}};
T.prototype.da=function(){if(null!=this.b){U(this,this.c.transitionDuration);var a=this.b;V(this,a);this.F!=a&&(0==a?y("reachleftend",this):a==this.a-1&&y("reachrightend",this))}};
T.prototype.ca=function(a){if(this.a){if(0<this.c.H.length){var b=this.i.style["pointer-events"];this.i.style["pointer-events"]="none";var c=null;if((a=document.elementFromPoint(a.clientX,a.clientY))&&l(this.g,a))for(var d=0;d<this.a;d++)if(l(this.frames[d],a)){c=d;break}this.i.style["pointer-events"]=b;null!=c&&(b=this.c.H[c])&&!y("frameexit",this,{url:b}).detail.handled&&window.open(b)}G(this,"frametap")}};
var U=function(a,b){a.G=0<b;a.g&&O(a.g,b);for(var c=0;c<a.a;++c)O(a.frames[c],b)},V=function(a,b){a.frames[b]&&(a.b=b,Z(a,b,0,a.a),a.D.push("frameshown"),a.v[b]||(a.v[b]=!0,--a.I||a.D.push("allframesviewed")));a.G||a.l()},Z=function(a,b,c,d){for(var e=a.c,h,g=d||1,k=-g;k<=g;++k)if((d=a.frames[k+b])&&0<=c*k){0>k?h=1-Math.abs(c):0<k?h=Math.abs(c)-1:(S(a,b),a.b=b,h=c);var n=Math.abs(h);N(d,e.$*h,e.L*n,e.aa*n,e.Z*h)}a.K!=a.b&&null!=a.b&&(a.K=a.b,G(a,"frameactivated"));N(a.g,a.u-(b+c+.5)*e.s,-e.L,0)},
Y=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.f;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.f=document.createElement("gwd-gallerynavigation"),a.f.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.f)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.f),a.f=null);a.f&&(v(a,"navigation-highlight",a.f,"highlight"),v(a,"navigation-thumbnails",a.f,"use-thumbnails"));X(a)};document.registerElement("gwd-carouselgallery",{prototype:T.prototype});}).call(this);
