-function(){"use strict";var f;var k=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},l=function(a){if(k(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&k(a))return a;return null},m=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},p=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var q=["-ms-","-moz-","-webkit-",""],r=function(a,b,c,d){for(var e,g,h=0;h<q.length;++h)e=q[h]+b,g=(d?q[h]:"")+c,a.style.setProperty(e,g)};var t=function(a,b){return setInterval(a,b)};var u=function(a,b,c){var d;c?(d=document.createEvent("CustomEvent"),d.initCustomEvent(a,!0,!0,c)):(d=document.createEvent("Event"),d.initEvent(a,!0,!0));b.dispatchEvent(d);return d},v=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var w=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var x=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},y=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(x(w(a[c])))}return b},z=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];"img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")&&(null!=b?e.setAttribute("scaling",b):e.removeAttribute("scaling"))}},A=function(a,b){for(var c=b.length,d=b.splice(0,c),e,g=0;g<c;g++)e=d[g],"frameshown"==
e?u(e,a,{id:a.currentIndex}):u(e,a)},B=function(a,b){return(a%b+b)%b};var C=function(a){var b=m(a,"frame-width",-1);-1==b&&(b=parseInt(.8*a.clientWidth,10));var c=a.hasAttribute("show-reflection"),d=m(a,"frame-height",-1);-1==d&&(d=c?parseInt(4*a.clientHeight/7,10):parseInt(6*a.clientHeight/7,10));var e=m(a,"neighbor-translation-x",-1);-1==e&&(e=parseInt(b/8,10));var g=m(a,"neighbor-translation-y",-1);-1==g&&(g=parseInt(d/-10,10));var h=m(a,"neighbor-translation-z",-1);-1==h&&(h=-d);return{autoplay:a.hasAttribute("autoplay"),l:b,N:d,T:m(a,"neighbor-rotation-y",38),
U:e,H:g,V:h,transitionDuration:m(a,"transition-duration",600),ba:c,aa:m(a,"start-frame",2)}},D=function(a,b,c,d,e){b="translate3d("+b+"px, "+c+"px, "+d+"px)";e&&(b="rotate3d(0, 1, 0, "+e+"deg) "+b);r(a,"transform",b)},E=function(a,b){r(a,"transition","transform "+b+"ms",!0)};var G=function(){};goog.inherits(G,HTMLElement);f=G.prototype;
f.createdCallback=function(){this.w=!1;this.h=null;this.a=0;this.G=this.f=-1;this.B=0;this.c=[];var a=document.createElement("gwd-gesture");a.className="gesture";this.v=a;this.M=this.Z.bind(this);this.L=this.$.bind(this);this.K=this.Y.bind(this);this.J=this.X.bind(this);this.s=u.bind(null,"firstinteraction",this);this.I=this.W.bind(this);this.C=!1;this.A=[];this.j=A.bind(null,this,this.A);this.o=[];this.O=1;this.F=0;if(this.u=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.b=
null;this.D=this.m=0;this.g=this.i=null;Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.P.bind(this)});Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.S.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.R.bind(this)})};
f.attachedCallback=function(){var a=this.v;this.m=this.m||this.clientWidth/2;a.addEventListener("trackstart",this.M,!1);a.addEventListener("track",this.L,!1);a.addEventListener("trackend",this.K,!1);a.addEventListener("tap",this.J,!1);this.addEventListener("transitionend",this.j,!1);this.addEventListener("webkitTransitionEnd",this.j,!1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=l(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&
this.gwdLoad()}};f.detachedCallback=function(){var a=this.v;a.removeEventListener("trackstart",this.M,!1);a.removeEventListener("track",this.L,!1);a.removeEventListener("trackend",this.K,!1);a.removeEventListener("tap",this.J,!1);this.removeEventListener("transitionend",this.j);this.removeEventListener("webkitTransitionEnd",this.j)};f.P=function(){return this.a?this.f+1:void 0};
f.goToFrame=function(a,b){var c="none"!=b,d=this.b.transitionDuration;0<a&&a<=this.a&&(this.stopRotation(),H(this,c?d:0),I(this,a-1))};f.goBackwards=function(a){this.goToFrame(this.currentIndex-1,a||"slide")};f.goForwards=function(a){this.goToFrame(this.currentIndex+1,a||"slide")};
f.rotateOnce=function(a,b){var c=a||this.b.transitionDuration*this.a,d=b||"forwards",e=this.b.transitionDuration;this.a&&!this.i&&(this.D=this.f,H(this,e),J(this,B(this.f+("left"==d||"backwards"==d?-1:1),this.a),0),this.i=t(function(){J(this,B(this.f+("left"==d||"backwards"==d?-1:1),this.a),0);this.D==this.f&&this.stopRotation()}.bind(this),c/this.a))};f.stopRotation=function(){this.i&&(clearInterval(this.i),this.i=null)};f.gwdIsLoaded=function(){return this.w};
f.gwdLoad=function(){if(!this.w&&!this.h){var a;if(this.u)a=y(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.c=a;K(this)}};f.getFrame=function(a){return this.c&&this.c[a-1]};
var K=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.g=null;a.h&&a.h.removeEventListener("pageload",a.I,!1);for(var b=a.c,c=document.createElement("div","gwd-page"),d,e=0;e<b.length;++e)d=b[e],r(d,"user-select","none"),d.classList.add("frame"),c.appendChild(d);v(c,c.gwdLoad.bind(c));a.h=c;c.className=a.hasAttribute("show-reflection")?"container reflection":"container";c.addEventListener("pageload",a.I,!1);z(a.c,a.getAttribute("scaling"));a.appendChild(c);a.appendChild(a.v)};f=G.prototype;
f.W=function(a){if(this.h===a.target){this.w=!0;this.a=this.c.length;this.o=[];this.F=this.a;this.b=C(this);a=0;for(var b,c=0;c<this.c.length;c++)b=this.c[c],b.style.left=a+"px",b.style.width=this.b.l+"px",b.style.height=this.b.N+"px",a+=this.b.l;if(this.a){a=this.b.aa-1;if(0>a||a>=this.a)a=0;H(this,0);I(this,a);this.b.autoplay&&setTimeout(this.rotateOnce.bind(this),0)}L(this);u("allframesloaded",this);u("ready",this)}};
f.attributeChangedCallback=function(a){switch(a){case "images":this.u=!0;this.a=0;this.f=-1;this.c=y(this.getAttribute(a));K(this);break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":L(this);break;case "scaling":z(this.c,this.getAttribute("scaling"));break;case "style":case "class":break;default:this.b=C(this)}};f.Z=function(){this.a&&(this.stopRotation(),this.B=this.f,H(this,0))};
f.$=function(a){if(this.a){this.s&&(this.s(),this.s=null);a=-a.dx/this.b.l;var b=Math.round(a);J(this,this.B+b,a-b)}};f.Y=function(){if(this.a){H(this,this.b.transitionDuration);var a=this.f;I(this,a);this.B!=a&&(0==a?u("reachleftend",this):a==this.a-1&&u("reachrightend",this))}};f.X=function(){this.a&&u("frametap",this,{id:this.currentIndex})};
var H=function(a,b){a.C=0<b;a.h&&E(a.h,b);for(var c=0;c<a.a;++c)E(a.c[c],b)},I=function(a,b){a.c[b]&&(a.f=b,J(a,b,0,a.a),a.A.push("frameshown"),a.o[b]||(a.o[b]=!0,--a.F||a.A.push("allframesviewed")));a.C||a.j()},J=function(a,b,c,d){for(var e=a.b,g,h=d||1,n=-h;n<=h;++n)if((d=a.c[n+b])&&0<=c*n){0>n?g=1-Math.abs(c):0<n?g=Math.abs(c)-1:(a.f=b,g=c);var F=Math.abs(g);D(d,e.U*g,e.H*F,e.V*F,e.T*g)}a.G!=a.f&&(a.G=a.f,u("frameactivated",a,{id:a.currentIndex}));D(a.h,a.m-(b+c+.5)*e.l,-e.H,0)},L=function(a){var b=
a.hasAttribute("has-navigation"),c=!!a.g;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.g=document.createElement("gwd-gallerynavigation"),a.g.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.g)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.g),a.g=null);a.g&&(p(a,"navigation-highlight",a.g,"highlight"),p(a,"navigation-thumbnails",a.g,"use-thumbnails"))};G.prototype.S=function(){return this.O};G.prototype.R=function(){return this.a};
document.registerElement("gwd-carouselgallery",{prototype:G.prototype});}()
