(function(){var f;var h=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},aa=function(a){if(h(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&h(a))return a;return null},k=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},l=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a},n=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var v=function(a,b){return a.x*b.x+a.y*b.y},z=function(a,b){return y(b,v(a,b))},y=function(a,b){return B(a.x*b,a.y*b)},B=function(a,b){return{x:a,y:void 0!==b?b:a}};var C=function(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Fa=function(a,c,q){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var D=["-ms-","-moz-","-webkit-",""],E=function(a,b,c){for(var d,e,q=0;q<D.length;++q)d=D[q]+b,e=""+c,a.style.setProperty(d,e)};var G=function(a,b,c){if(c){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);b.dispatchEvent(d);return d},ba=function(a,b){setTimeout(function(){G("autoplayended",a,b)},0)},ca=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var da=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var ea=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},H=function(a){this.m=a;this.s=null;this.Ea=!0;this.M=!1};
H.prototype.play=function(a,b,c){if(this.m.frameCount&&null==this.s){b=b||"forwards";if(c){var d=Math.floor(a/c);a=c}else d=this.m.frameCount,a/=d;var e=[],q=ea(this.m);c=q;for(var p=0;p<d;p++){if(0<p||!this.Ea)c=J(c+K(b,1),this.m.frameCount);e.push(c)}b=function(){if(e.length){var a=e.shift();this.M=!0;this.m.goToFrame(a+1);this.M=!1;var b=this.m;G("frameautoplayed",b,{id:a+1||b.currentIndex})}else this.stop(!0),this.m.goToFrame(q+1)}.bind(this);this.s=setInterval(b,a);setTimeout(b)}};
H.prototype.stop=function(a){!this.M&&this.s&&(clearInterval(this.s),ba(this.m,{completed:!!a}),this.s=null)};
var fa=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},L=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(fa(da(a[c])))}return b},M=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];"img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")&&(null!=b?e.setAttribute("scaling",b):e.removeAttribute("scaling"))}},ha=function(a,b){var c=b.length;b=b.splice(0,c);for(var d,e=0;e<c;e++)d=b[e],"frameshown"==
d?G(d,a,{id:a.currentIndex}):G(d,a)},K=function(a,b){return"left"==a||"backwards"==a?-b:b},J=function(a,b){return(a%b+b)%b},ia=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.pause()})},ja=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.play()})};var N=function(){};C(N,HTMLElement);f=N.prototype;f.createdCallback=function(){this.frames=[];this.b=null;this.a=0;this.l=1;this.v=new H(this);Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.na.bind(this)});Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.qa.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.pa.bind(this)});this.ga=this.hasAttribute("pause-front-media");this.ha=this.hasAttribute("resume-next-media")};
f.attributeChangedCallback=function(a){switch(a){case "pause-front-media":this.ga=this.hasAttribute("pause-front-media");break;case "resume-next-media":this.ha=this.hasAttribute("resume-next-media")}};f.getFrame=function(a){if(0!=this.a)return this.frames[a-1]};f.gwdLoad=function(){};f.gwdIsLoaded=function(){return!0};f.goToFrame=function(a,b){this.stopRotation();0!=this.a&&(a>this.a?a=this.a:1>a&&(a=1),this.Z(a,b))};f.Z=function(a){this.b=a-1};
var O=function(a,b,c,d){if(null!=a.b){var e=J(a.b+K(b,a.l||1),a.l*Math.ceil(a.a/a.l));null!=d&&!d&&("forwards"==b&&e<a.b||"backwards"==b&&e>a.b)||a.goToFrame(e+1,c||"slide")}};f=N.prototype;f.goBackwards=function(a,b){return O(this,"backwards",a,b)};f.goForwards=function(a,b){return O(this,"forwards",a,b)};f.rotateOnce=function(a,b){this.v.play(a||0,b)};f.stopRotation=function(){this.v.stop()};f.na=function(){return 0<this.a?this.b+1:void 0};f.qa=function(){return this.l};f.pa=function(){return this.a};var P=function(){};C(P,N);
P.prototype.createdCallback=function(){P.C.createdCallback.call(this);this.N=!1;this.O=this.c=null;if(this.Y=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.o=B(0);var a=document.createElement("gwd-gesture");a.className="gesture";this.L=a;this.j=!1;this.f=null;this.ca=this.xa.bind(this);this.ea=this.za.bind(this);this.aa=this.va.bind(this);this.ba=this.wa.bind(this);this.da=this.ya.bind(this);this.V=this.sa.bind(this);this.ma=this.Ca.bind(this);this.la=this.Ba.bind(this);
this.ka=this.Aa.bind(this);this.X=this.ta.bind(this);this.fa=this.ua.bind(this);this.H=G.bind(null,"firstinteraction",this);this.R=!1;this.A=[];this.u=ha.bind(null,this,this.A);this.ia=this.ja=this.F=this.T=this.S=0;this.K=1;this.G=[];this.J=0;this.Da=.7;this.B=0;this.D=!1;this.P=B(0);this.I=B(0);this.h=null;this.g=this.$=-1;this.W=[];this.w=B(-1,-1);a="y"==this.getAttribute("swipe-axis");this.i=B(a?0:1,a?1:0);Object.defineProperty(this,"firstVisibleFrameIndex",{enumerable:!0,get:this.oa.bind(this)});
Object.defineProperty(this,"lastVisibleFrameIndex",{enumerable:!0,get:this.ra.bind(this)})};
P.prototype.attachedCallback=function(){var a=this.L;a.addEventListener("pointerover",this.ea,!1);a.addEventListener("pointerout",this.ca,!1);a.addEventListener("pointermove",this.aa,!1);a.addEventListener("track",this.ma,!1);a.addEventListener("trackend",this.la,!1);a.addEventListener("tap",this.ka,!1);this.addEventListener("frametap",this.X,!1);this.addEventListener("swipefinished",this.U,!1);this.addEventListener("transitionend",this.u,!1);this.addEventListener("webkitTransitionEnd",this.u,!1);
if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=aa(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
P.prototype.detachedCallback=function(){var a=this.L;a.removeEventListener("pointerover",this.ea,!1);a.removeEventListener("pointerout",this.ca,!1);a.removeEventListener("pointermove",this.aa,!1);a.removeEventListener("track",this.ma,!1);a.removeEventListener("trackend",this.la,!1);a.removeEventListener("tap",this.ka,!1);this.removeEventListener("frametap",this.X,!1);this.removeEventListener("swipefinished",this.U,!1);this.removeEventListener("transitionend",this.u);this.removeEventListener("webkitTransitionEnd",
this.u)};
P.prototype.attributeChangedCallback=function(a){P.C.attributeChangedCallback.call(this,a);switch(a){case "images":this.frames=L(this.getAttribute("images"));Q(this);R(this);break;case "scaling":M(this.frames,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":S(this);R(this);break;case "transition-duration":case "exit-urls":case "autoplay-duration":case "autoplay-step-interval":T(this);break;case "frame-width":case "frame-height":case "frame-snap-interval":case "num-frames-to-display":T(this);R(this);
break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":R(this)}};
var T=function(a){var b=k(a,"num-frames-to-display",1),c=k(a,"frame-snap-interval",1),d=k(a,"transition-duration",600),e=k(a,"frame-width",-1),q=k(a,"frame-height",-1);var p=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"";var g=l(a,"autoplay-duration",3E3),t=l(a,"autoplay-step-interval",0);a.w.x=e;a.w.y=q;-1!=v(a.w,a.i)?b=-1:0<b&&c>b&&(c=b);a.W=p.split(/,/g);a.g=b;a.l=c;a.F=d;a.S=g;a.T=t},R=function(a){var b=B(a.clientWidth,a.clientHeight);a.h&&(b.y-=36,a.O.style.height=b.y+"px");var c=
a.i,d=y(c,k(a,"offset",0)),e=l(a,"swipe-threshold-ratio",.1),q=l(a,"swipe-committed-threshold-ratio",.5),p=a.g,g=a.w;g=B(-1==g.x?b.x:g.x,-1==g.y?b.y:g.y);if(a.hasAttribute("offset")){a:{var t=g.x;var m=g.y;b:switch(a.getAttribute("clamp-frame-size-to-image")){case "true":var u=!0;break b;case "false":u=!1;break b;default:u=!0}if(u){var w=a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain";if((u="contain"==w)||"none"==w){var F=-1;w=-1;for(var ka=a.frameCount,I=0;I<ka;I++){var r=a.getFrame(I+
1);if("img"!=r.tagName.toLowerCase()||"gwd-image"!=r.getAttribute("is"))break a;var x=r;r=x.assetWidth;var A=x.assetHeight;0<r&&0<A&&(u?r/A<t/m?(x=r/A*m,r=m):(x=t,r=A/r*t):(x=r,r=A),F=Math.max(F,x),w=Math.max(w,r))}t=-1!=F?Math.min(t,F):t;m=-1!=w?Math.min(m,w):m}}}1==c.x?g.x=t:g.y=m}1<p&&(m=y(c,p-1),m=B(m.x*d.x,m.y*d.y),p=z(B((b.x-m.x)/p,(b.y-m.y)/p),c),p.x&&(g.x=p.x),p.y&&(g.y=p.y));p=k(a,"start-frame",2<a.g?1+Math.ceil(a.g/2-1):1);t=a.hasAttribute("disable-gesture");m=z(B(g.x+d.x,g.y+d.y),c);u=
1+2*Math.floor((v(c,b)-v(c,g))/(2*v(c,m)));if(1>u||!isFinite(u))u=1;b=B((b.x-g.x)/2,(b.y-g.y)/2);0<a.g&&0==a.g%2&&(d=z(B(g.x+d.x,g.y+d.y),c),b.x-=.5*d.x,b.y-=.5*d.y,u+=1);a.I=g;a.P=b;a.K=u;a.B=v(m,a.i);a.j=t;a.ja=v(g,c)*e;a.ia=v(g,c)*q;e=z(b,B(c.y,c.x));for(d=0;d<a.a;d++)q=a.frames[d].style,q.left=e.x+"px",q.top=e.y+"px",q.width=g.x+"px",q.height=g.y+"px",e.x+=m.x,e.y+=m.y;a.o=B(0);a.c&&(U(a,0,0,0),c=z(b,c),a.c.style.left=c.x+"px",a.c.style.top=c.y+"px");a.b=null;a.goToFrame(p,"none")};f=P.prototype;
f.gwdIsLoaded=function(){return this.N};f.gwdLoad=function(){if(!this.N&&!this.c){if(this.Y)var a=L(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;Q(this)}};f.goBackwards=function(a,b){return P.C.goBackwards.call(this,a,null!=b?b:!1)};f.goForwards=function(a,b){return P.C.goForwards.call(this,a,null!=b?b:!1)};
f.Z=function(a,b){var c=a-1;c-=c%this.l;c+=Math.floor((this.l-1)/2);0>c?c=0:c>=this.a&&(c=this.a-1);if(1<this.g){a=V(this,c);var d=a+this.g-1;1>a&&(c+=1-a);d>this.a&&(c-=d-this.a)}a=c;null!=this.b&&this.b!=a&&(this.ga&&ia(this.frames[this.b]),this.ha&&ja(this.frames[a]));a=this.b;this.b=c;c=y(this.i,-this.B*this.b);U(this,"none"!=b?this.F:0,c.x,c.y);this.o=c;if(this.J)for(b=Math.floor((this.K-1)/2),c=0;c<this.K;c++)if(d=this.b-b+c,!(0>d||d>=this.a||this.G[d]||(this.G[d]=!0,--this.J))){this.A.push("allframesviewed");
break}a!=this.b&&(W(this,this.b+1),this.A.push("frameshown"),this.A.push("swipefinished"));this.R||this.u()};
var U=function(a,b,c,d){a.R=0<b;E(a.c,"transition","transform "+b+"ms");E(a.c,"transform","translate3d("+c+"px,"+d+"px,0)")},Q=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.h=null;a.c&&(a.c.removeEventListener("pageload",a.fa,!1),a.c.removeEventListener("mouseover",a.da,!0),a.c.removeEventListener("mouseout",a.ba,!0),a.c.removeEventListener("click",a.V,!0));for(var b=a.frames,c=document.createElement("div","gwd-page"),d,e=0;e<b.length;++e)d=b[e],E(d,"user-select","none"),d.classList.add("frame"),
c.appendChild(d);ca(c,c.gwdLoad.bind(c));a.c=c;c.className="container";a.c.addEventListener("pageload",a.fa,!1);a.c.addEventListener("mouseover",a.da,!0);a.c.addEventListener("mouseout",a.ba,!0);a.c.addEventListener("click",a.V,!0);M(a.frames,a.getAttribute("scaling"));a.a=a.frames.length;b=document.createElement("div");a.O=b;b.className="matte";b.appendChild(c);a.appendChild(a.O);a.appendChild(a.L)};P.prototype.U=function(){E(this.c,"transition","transform 0ms")};
P.prototype.ua=function(a){a.target===this.c&&(this.N=!0,this.J=this.a,this.G=[],T(this),S(this),R(this),G("allframesloaded",this),this.hasAttribute("autoplay")&&this.v.play(this.S,"forwards",this.T),G("ready",this))};P.prototype.rotateOnce=function(a,b){this.v.play(a||this.F,b)};
var Y=function(a,b){var c=a.a;if(c){var d=a.b;b=X(a,b);a.goToFrame(b+1);d!=b&&(0==b?G("reachleftend",a):b==c-1&&G("reachrightend",a))}},S=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.h;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.h=document.createElement("gwd-gallerynavigation"),a.h.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.h)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.h),a.h=null);a.h&&(n(a,"navigation-highlight",a.h,"highlight"),
n(a,"navigation-thumbnails",a.h,"use-thumbnails"))},X=function(a,b){var c=a.b;Math.abs(b)>a.ja&&(c=0>b?c+a.l:c-a.l);0>c?c=0:c>=a.a&&(c=a.a-1);return c},W=function(a,b){a.$!=b&&(a.$=b,G("frameactivated",a,{id:b||a.currentIndex}))};
P.prototype.Ca=function(a){if(!this.j&&(this.H&&(this.H(),this.H=null),!this.D))if(this.stopRotation(),a=v(B(a.dx,a.dy),this.i),W(this,X(this,a)+1),Math.abs(a)>this.ia)Y(this,a),this.D=!0;else{if(0<a&&0===this.b||0>a&&this.b===this.a-1)a-=a*this.Da;U(this,0,this.o.x+this.i.x*a,this.o.y+this.i.y*a)}};P.prototype.Ba=function(a){this.j||(this.D?this.D=!1:Y(this,v(B(a.dx,a.dy),this.i)))};
var Z=function(a,b){var c=a.getBoundingClientRect();b=B(b.clientX-c.left,b.clientY-c.top);c=a.i;var d=B(c.y,c.x);c=v(d,b);var e=v(d,a.P);d=v(d,a.I);if(c<e||c>e+d)return null;c=a.i;b=v(c,b)-v(c,a.o)-v(c,a.P);c=Math.floor(b/a.B);return 0>c||c>=a.a||b%a.B>v(a.i,a.I)?null:c};f=P.prototype;f.Aa=function(a){this.j||(this.stopRotation(),a=Z(this,a),null!=a&&G("frametap",this,{element:this.frames[a],id:a+1}))};
f.ta=function(a){(a=a.detail&&a.detail.id)&&(a=this.W[a-1])&&!G("frameexit",this,{url:a}).detail.handled&&window.open(a)};f.xa=function(){this.j||null==this.f||(G("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),this.f=null)};f.za=function(a){this.j||(a=Z(this,a),a!=this.f&&(null!=this.f&&G("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),null!=a&&G("framemouseover",this,{element:this.frames[a],id:1+a}),this.f=a))};
f.va=function(a){this.j||(a=Z(this,a),a!=this.f&&(null!=this.f&&G("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),null!=a&&G("framemouseover",this,{element:this.frames[a],id:1+a}),this.f=a))};f.ya=function(a){this.j&&a.target.classList.contains("frame")&&G("framemouseover",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};f.wa=function(a){this.j&&a.target.classList.contains("frame")&&G("framemouseout",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};
f.sa=function(a){this.j&&a.target.classList.contains("frame")&&G("frametap",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};var V=function(a,b){return 1+(void 0!==b?b:a.b)-Math.floor((a.g-1)/2)};P.prototype.oa=function(){if(0<this.g&&0<this.a)return Math.max(1,V(this))};P.prototype.ra=function(){if(0<this.g&&0<this.a)return Math.min(this.a,V(this)+this.g-1)};document.registerElement("gwd-swipegallery",{prototype:P.prototype});}).call(this);
