-function(){"use strict";var h;var k=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},m=function(a){if(k(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&k(a))return a;return null},n=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},q=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a},r=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var u=function(a,b){return a.x*b.x+a.y*b.y},w=function(a,b){return v(b,u(a,b))},v=function(a,b){return x(a.x*b,a.y*b)},x=function(a,b){return{x:a,y:void 0!==b?b:a}};var y=function(a,b){return setInterval(a,b)};var z=["-ms-","-moz-","-webkit-",""],A=function(a,b,c){for(var d,e,g=0;g<z.length;++g)d=z[g]+b,e=""+c,a.style.setProperty(d,e)};var B=function(a,b,c){var d;c?(d=document.createEvent("CustomEvent"),d.initCustomEvent(a,!0,!0,c)):(d=document.createEvent("Event"),d.initEvent(a,!0,!0));b.dispatchEvent(d);return d},C=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var D=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var E=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},F=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(E(D(a[c])))}return b},G=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];"img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")&&(null!=b?e.setAttribute("scaling",b):e.removeAttribute("scaling"))}},H=function(a,b){for(var c=b.length,d=b.splice(0,c),e,g=0;g<c;g++)e=d[g],"frameshown"==
e?B(e,a,{id:a.currentIndex}):B(e,a)};var I=function(){};goog.inherits(I,HTMLElement);
I.prototype.createdCallback=function(){this.J=!1;this.K=this.c=null;this.f=[];this.b=null;if(this.S=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.s=x(0);var a=document.createElement("gwd-gesture");a.className="gesture";this.I=a;this.l=!1;this.g=null;this.W=this.ma.bind(this);this.Y=this.oa.bind(this);this.U=this.ka.bind(this);this.V=this.la.bind(this);this.X=this.na.bind(this);this.O=this.ha.bind(this);this.da=this.ra.bind(this);this.ca=this.qa.bind(this);
this.ba=this.pa.bind(this);this.R=this.ia.bind(this);this.Z=this.ja.bind(this);this.D=B.bind(null,"firstinteraction",this);this.N=!1;this.M=[];this.u=H.bind(null,this,this.M);this.$=this.aa=this.B=0;this.o=null;this.a=0;this.H=1;this.C=[];this.G=0;this.h=1;this.sa=.7;this.w=0;this.A=!1;this.L=x(0);this.F=x(0);this.i=null;this.m=this.T=-1;this.P=[];this.v=x(-1,-1);a="y"==this.getAttribute("swipe-axis");this.j=x(a?0:1,a?1:0);Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.ea.bind(this)});
Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.ga.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.fa.bind(this)})};
I.prototype.attachedCallback=function(){var a=this.I;a.addEventListener("pointerover",this.Y,!1);a.addEventListener("pointerout",this.W,!1);a.addEventListener("pointermove",this.U,!1);a.addEventListener("track",this.da,!1);a.addEventListener("trackend",this.ca,!1);a.addEventListener("tap",this.ba,!1);this.addEventListener("frametap",this.R,!1);this.addEventListener("transitionend",this.u,!1);this.addEventListener("webkitTransitionEnd",this.u,!1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&
!this.gwdIsLoaded()){var b=(a=m(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
I.prototype.detachedCallback=function(){var a=this.I;a.removeEventListener("pointerover",this.Y,!1);a.removeEventListener("pointerout",this.W,!1);a.removeEventListener("pointermove",this.U,!1);a.removeEventListener("track",this.da,!1);a.removeEventListener("trackend",this.ca,!1);a.removeEventListener("tap",this.ba,!1);this.removeEventListener("frametap",this.R,!1);this.removeEventListener("transitionend",this.u);this.removeEventListener("webkitTransitionEnd",this.u)};
I.prototype.attributeChangedCallback=function(a){switch(a){case "images":this.f=F(this.getAttribute("images"));J(this);K(this);break;case "scaling":G(this.f,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":L(this);K(this);break;case "frame-snap-interval":case "transition-duration":case "exit-urls":M(this);break;case "frame-width":case "frame-height":case "num-frames-to-display":M(this);K(this);break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":K(this)}};
var M=function(a){var b=n(a,"num-frames-to-display",1),c=n(a,"frame-snap-interval",1),d=n(a,"transition-duration",600),e=n(a,"frame-width",-1),g=n(a,"frame-height",-1),p;p=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"";a.v.x=e;a.v.y=g;-1!=u(a.v,a.j)?b=-1:0<b&&c>b&&(c=b);e=p.split(/,/g);a.m=b;a.h=c;a.B=d;a.P=e},K=function(a){var b=x(a.clientWidth,a.clientHeight);a.i&&(b.y-=36,a.K.style.height=b.y+"px");var c=a.j,d=v(c,n(a,"offset",0)),e=q(a,"swipe-threshold-ratio",.1),g=q(a,"swipe-committed-threshold-ratio",
.5),p=a.m,f=a.v,f=x(-1==f.x?b.x:f.x,-1==f.y?b.y:f.y),l=x(0);1<p&&(l=v(c,p-1),l=x(l.x*d.x,l.y*d.y),l=w(x((b.x-l.x)/p,(b.y-l.y)/p),c),l.x&&(f.x=l.x),l.y&&(f.y=l.y));var p=n(a,"start-frame",a.m?1+Math.ceil(a.m/2-1):1),T=a.hasAttribute("disable-gesture"),l=w(x(f.x+d.x,f.y+d.y),c),t;t=1+2*Math.floor((u(c,b)-u(c,f))/(2*u(c,l)));if(1>t||!isFinite(t))t=1;b=x((b.x-f.x)/2,(b.y-f.y)/2);0<a.m&&0==a.m%2&&(d=w(x(f.x+d.x,f.y+d.y),c),b.x-=.5*d.x,b.y-=.5*d.y,t+=1);a.F=f;a.L=b;a.H=t;a.w=u(l,a.j);a.l=T;a.aa=u(f,c)*
e;a.$=u(f,c)*g;e=w(b,x(c.y,c.x));for(d=0;d<a.a;d++)g=a.f[d].style,g.left=e.x+"px",g.top=e.y+"px",g.width=f.x+"px",g.height=f.y+"px",e.x+=l.x,e.y+=l.y;a.s=x(0);a.c&&(N(a,0,0,0),c=w(b,c),a.c.style.left=c.x+"px",a.c.style.top=c.y+"px");a.b=null;O(a,p,"none")};I.prototype.gwdIsLoaded=function(){return this.J};
I.prototype.gwdLoad=function(){if(!this.J&&!this.c){var a;if(this.S)a=F(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.f=a;J(this)}};I.prototype.goToFrame=function(a,b){O(this,a,b);this.stopRotation()};
var O=function(a,b,c){if(0!=a.a){b>a.a?b=a.a:1>b&&(b=1);var d=b-1,d=d-d%a.h,d=d+Math.floor((a.h-1)/2);d>=a.a&&(d=a.a-1);b=a.b;a.b=d;d=v(a.j,-a.w*a.b);N(a,"none"!=c?a.B:0,d.x,d.y);a.s=d;if(a.G)for(c=Math.floor((a.H-1)/2),d=0;d<a.H;d++){var e=a.b-c+d;if(!(0>e||e>=a.a||a.C[e]||(a.C[e]=!0,--a.G))){a.M.push("allframesviewed");break}}b!=a.b&&(P(a,a.b+1),a.M.push("frameshown"));a.N||a.u()}},N=function(a,b,c,d){a.N=0<b;A(a.c,"transition","all "+b+"ms");A(a.c,"transform","translate3d("+c+"px,"+d+"px,0)")},
J=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.i=null;a.c&&(a.c.removeEventListener("pageload",a.Z,!1),a.c.removeEventListener("mouseover",a.X,!0),a.c.removeEventListener("mouseout",a.V,!0),a.c.removeEventListener("click",a.O,!0));for(var b=a.f,c=document.createElement("div","gwd-page"),d,e=0;e<b.length;++e)d=b[e],A(d,"user-select","none"),d.classList.add("frame"),c.appendChild(d);C(c,c.gwdLoad.bind(c));a.c=c;c.className="container";a.c.addEventListener("pageload",a.Z,!1);a.c.addEventListener("mouseover",
a.X,!0);a.c.addEventListener("mouseout",a.V,!0);a.c.addEventListener("click",a.O,!0);G(a.f,a.getAttribute("scaling"));a.a=a.f.length;b=document.createElement("div");a.K=b;b.className="matte";b.appendChild(c);a.appendChild(a.K);a.appendChild(a.I)};h=I.prototype;
h.ja=function(a){a.target===this.c&&(this.J=!0,this.G=this.a,this.C=[],M(this),L(this),K(this),B("allframesloaded",this),this.hasAttribute("autoplay")&&(a=parseInt(this.getAttribute("autoplay-duration"),10)||3E3,setTimeout(this.rotateOnce.bind(this,a),0)),B("ready",this))};
h.rotateOnce=function(a,b){if(this.a&&!this.o){for(var c=a||this.B,d=b||"forwards",e=Math.ceil(this.a/this.h),g=Math.floor(this.b/this.h),p=[],f=1;f<e;f++)p.push((e+("forwards"==d?g+f:g-f))%e*this.h);p.push(this.b);var l=0;this.o=y(function(){O(this,p[l++]+1);l>=p.length&&this.stopRotation()}.bind(this),c/p.length)}};h.ea=function(){return 0<this.a?this.b+1:void 0};h.getFrame=function(a){return this.f[a-1]};h.goForwards=function(a){null!=this.b&&this.goToFrame(this.b+1+this.h,a||"slide")};
h.goBackwards=function(a){null!=this.b&&this.goToFrame(this.b+1-this.h,a||"slide")};h.stopRotation=function(){this.o&&(clearInterval(this.o),this.o=null)};
var R=function(a,b){var c=a.a;if(c){var d=a.b,e=Q(a,b);O(a,e+1);d!=e&&(0==e?B("reachleftend",a):e==c-1&&B("reachrightend",a))}},L=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.i;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.i=document.createElement("gwd-gallerynavigation"),a.i.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.i)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.i),a.i=null);a.i&&(r(a,"navigation-highlight",a.i,"highlight"),r(a,"navigation-thumbnails",
a.i,"use-thumbnails"))},Q=function(a,b){var c=a.b;Math.abs(b)>a.aa&&(c=0>b?c+a.h:c-a.h);0>c?c=0:c>=a.a&&(c=a.a-1);return c},P=function(a,b){a.T!=b&&(a.T=b,B("frameactivated",a,{id:b||a.currentIndex}))};I.prototype.ra=function(a){if(!this.l&&(this.D&&(this.D(),this.D=null),!this.A))if(this.stopRotation(),a=u(x(a.dx,a.dy),this.j),P(this,Q(this,a)+1),Math.abs(a)>this.$)R(this,a),this.A=!0;else{if(0<a&&0===this.b||0>a&&this.b===this.a-1)a-=a*this.sa;N(this,0,this.s.x+this.j.x*a,this.s.y+this.j.y*a)}};
I.prototype.qa=function(a){this.l||(this.A?this.A=!1:R(this,u(x(a.dx,a.dy),this.j)))};var S=function(a,b){var c=a.getBoundingClientRect(),c=x(b.clientX-c.left,b.clientY-c.top),d=a.j,e=x(d.y,d.x),d=u(e,c),g=u(e,a.L),e=u(e,a.F);if(d<g||d>g+e)return null;d=a.j;c=u(d,c)-u(d,a.s)-u(d,a.L);d=Math.floor(c/a.w);return 0>d||d>=a.a||c%a.w>u(a.j,a.F)?null:d};h=I.prototype;h.pa=function(a){this.l||(this.stopRotation(),a=S(this,a),null!=a&&B("frametap",this,{element:this.f[a],id:a+1}))};
h.ia=function(a){(a=a.detail&&a.detail.id)&&(a=this.P[a-1])&&!B("frameexit",this,{url:a}).detail.handled&&window.open(a)};h.ma=function(){this.l||null==this.g||(B("framemouseout",this,{element:this.f[this.g],id:1+this.g}),this.g=null)};h.oa=function(a){this.l||(a=S(this,a),a!=this.g&&(null!=this.g&&B("framemouseout",this,{element:this.f[this.g],id:1+this.g}),null!=a&&B("framemouseover",this,{element:this.f[a],id:1+a}),this.g=a))};
h.ka=function(a){this.l||(a=S(this,a),a!=this.g&&(null!=this.g&&B("framemouseout",this,{element:this.f[this.g],id:1+this.g}),null!=a&&B("framemouseover",this,{element:this.f[a],id:1+a}),this.g=a))};h.na=function(a){this.l&&a.target.classList.contains("frame")&&B("framemouseover",this,{element:a.target,id:1+this.f.indexOf(a.target)})};h.la=function(a){this.l&&a.target.classList.contains("frame")&&B("framemouseout",this,{element:a.target,id:1+this.f.indexOf(a.target)})};
h.ha=function(a){this.l&&a.target.classList.contains("frame")&&B("frametap",this,{element:a.target,id:1+this.f.indexOf(a.target)})};h.ga=function(){return this.h};h.fa=function(){return this.a};document.registerElement("gwd-swipegallery",{prototype:I.prototype});}()
